---
development:
  cloud_name: dm0musx2l
  api_key: '331929771958591'
  api_secret: yb1JVP0mKaXqonZ6GCi93AhhC_g
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dm0musx2l
  api_key: '331929771958591'
  api_secret: yb1JVP0mKaXqonZ6GCi93AhhC_g
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dm0musx2l
  api_key: '331929771958591'
  api_secret: yb1JVP0mKaXqonZ6GCi93AhhC_g
  enhance_image_tag: true
  static_file_support: false
